name: selftest
run-name: selftest ${{ github.actor }} 
on: [workflow_dispatch]
jobs:
  selftest:
    name: selftest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: selftest
        uses: eriksette/token-action@v1
        with:
          pem-key: ${{ secrets.PEM_KEY }}
   